[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#8ec07c"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[cursor]
blink_interval = 750
blink_timeout = 5

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 7.4

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
