enable_audio_bell no

# Font
font_family CaskaydiaCove Nerd Font
font_size 9.0
disable_liagtures never

url_color #61afef
url_style curly

#
# Keymaps
#
map ctrl+shift+left neighboring_window left
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down
map ctrl+shift+right neighboring_window right

#
# Background
#
opacity 0.9

#
# Shell
#
shel zsh
