#!/bin/sh

sudo pacman -S --noconfirm gnu-free-fonts ttf-inconsolata noto-fonts-emoji nerd-fonts
sudo pacman -S --noconfirm neofetch zsh alacritty kitty bspwm sxhkd picom polybar rofi pulseaudio pavucontrol lxappearance git ly
sudo pacman -S --noconfirm lsd bat mdbat bashtop htop udev ntfs-3g reflector lxappearance
sudo pacman -S --noconfirm nvidia nvidia-settings nvidia-utils lib32-nvidia-utils cuda opencl-nvidia  lib32-opencl-nvidia vdpauinfo clinfo

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

# Configurar el archivo .zshrc para incluir los complementos recién instalados
sed -i 's/plugins=(git)/plugins=(git fast-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc

# Cambiar el tema de Oh My Zsh a Powerlevel10k
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k/powerlevel10k"/' ~/.zshrc

# Configurar el archivo .zshrc para habilitar completado de comandos con flechas
echo 'bindkey "^[[A" history-substring-search-up' >> ~/.zshrc
echo 'bindkey "^[[B" history-substring-search-down' >> ~/.zshrc
sudo pacman -S cloudflared
