#!/bin/sh

sudo pacman -S --noconfirm gnu-free-fonts ttf-inconsolata noto-fonts-emoji nerd-fonts
sudo pacman -S --noconfirm neofetch zsh alacritty kitty bspwm sxhkd picom polybar rofi pulseaudio pavucontrol lxappearance git ly
sudo pacman -S --noconfirm lsd bat mdbat bashtop htop udev ntfs-3g reflector lxappearance
sudo pacman -S --noconfirm nvidia nvidia-settings nvidia-utils lib32-nvidia-utils cuda opencl-nvidia  lib32-opencl-nvidia vdpauinfo clinfo

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

# Configurar el archivo .zshrc para incluir los complementos recién instalados
sed -i 's/plugins=(git)/plugins=(git fast-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc

# Cambiar el tema de Oh My Zsh a Powerlevel10k
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k/powerlevel10k"/' ~/.zshrc

# Configurar el archivo .zshrc para habilitar completado de comandos con flechas
echo 'bindkey "^[[A" history-substring-search-up' >> ~/.zshrc
echo 'bindkey "^[[B" history-substring-search-down' >> ~/.zshrc
sudo pacman -S cloudflared

# uninstall packages
sudo pacman -Rnsc kguiaddons-5.110.0-1  qt5-svg-5.15.10+kde+r8-1  qt5-wayland-5.15.10+kde+r62-1  qt5-x11extras-5.15.10-1  flameshot-12.1.0-2
sudo pacman -Rnsc btrfs-progs-6.5.1-1  fuse3-3.16.1-1  gcr-3.41.1-4  libaio-0.3.113-2  libatasmart-0.19-6  libblockdev-3.0.3-4  libbytesize-2.8-2  libcdio-2.1.0-3  libcdio-paranoia-10.2+2.0.1-3
              libnvme-1.5-1  lvm2-2.03.22-2  mdadm-4.2-2  parted-3.6-1  thin-provisioning-tools-1.0.6-1  udisks2-2.10.1-2  volume_key-0.3.12-8  gvfs-1.52.0-1
sudo pacman -S gvfs ncdu cronie pavucontrol nitrogen wmname
