## COLORSCHEME: Gruvbox-Dark

set-option -g status "on"
set-option -g status-justify "left"
set-option -g status-left-length 80
set-option -g status-right-length 80
set-window-option -g window-status-separator " "

# Barra de estado
set-option -g status-style bg=#3c3836,fg=#ebdbb2

# Ventana inactiva
set-window-option -g window-status-style bg=#fabd2f,fg=#3c3836

# Ventana con actividad
set-window-option -g window-status-activity-style bg=#3c3836,fg=#d5c4a1

# Ventana activa
set-window-option -g window-status-current-style bg=#cc241d,fg=#3c3836

# Bordes de los paneles
set-option -g pane-active-border-style fg=#a89984
set-option -g pane-border-style fg=#3c3836

# Mensajes
set-option -g message-style bg=#504945,fg=#ebdbb2
set-option -g message-command-style bg=#504945,fg=#ebdbb2

# Notificación de campana
set-window-option -g window-status-bell-style bg=#fb4934,fg=#3c3836

## Separadores en la barra de estado
set-option -g status-left "#[bg=#665c54,fg=#ebdbb2] #S  󰓩 #{session_windows} #[bg=#3c3836,fg=#665c54]"
set-option -g status-right "#[fg=#504945]#[bg=#504945,fg=#d5c4a1] 󰅐 #(uptime -p | sed \"s/up //; s/ days\\{0,1\\}/d/g; s/ hours\\{0,1\\}/h/g; s/ minutes\\{0,1\\}/m/g; s/,//g\") #[fg=#665c54]#[bg=#665c54,fg=#ebdbb2] 󰃶 %A   %H:%M #[fg=#fabd2f]#[bg=#fabd2f,fg=#282828] 󰀄 #(whoami)@#h "

# Formato de ventana activa e inactiva
set-window-option -g window-status-current-format "#[bg=#fabd2f,fg=#3c3836,nobold,noitalics,nounderscore]#[bg=#fabd2f,fg=#3c3836] #I #[bg=#fabd2f,fg=#3c3836,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#3c3836,fg=#fabd2f,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#504945,fg=#3c3836,noitalics]#[bg=#504945,fg=#ebdbb2] #I #[bg=#504945,fg=#ebdbb2] #W #[bg=#3c3836,fg=#504945,noitalics]"

## COLORSCHEME: Gruvbox-Dark END
