#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
/home/yoelvp/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII

bspc config border_width 1
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#e53935"

# Application
bspc rule -a Geany state=floating
bspc rule -a Alacritty desktop=^1
bspc rule -a firefox desktop=^2
bspc rule -a obsidian desktop=^3

# Set keyboard
setxkbmap latam &

# Cursor
xsetroot -cursor_name left_ptr &

# Feh
~/.fehbg &

# Transparency with picom
# picom -b --config ~/.config/picom/picom.conf

# Java apps
wmname LG3D &
