column_width = 120
line_endings = "Windows"
indent_type = "Spaces"
indent_width = 2
collapse_simple_statement = "Never"
quote_style = "AutoPreferSingle"
call_parentheses = "Always"

[sort_requires]
enabled = false
