#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII

bspc config border_width 1
bspc config window_gap 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#e53935"

bspc rule -a Firefox desktop='^2'

# Set keyboard
setxkbmap latam &

# Cursor
xsetroot -cursor_name left_ptr &

# Transparency
picom &

# Nitrogen
nitrogen --restore &
