;; ┌──────────────────────────────────┐
;; │ Created By Yoel Valverde @yoelvp │
;; └──────────────────────────────────┘

[module/checknet]
type = custom/script

; Available tokens:
;   %counter%
; Command to be executed (using "/usr/bin/env sh -c [command]")
exec = $HOME/dotfiles/Scripts/check-network

; Conditional command that, if defined, needs to exit successfully
; before the main exec command is invoked.
; Default: ""
;;exec-if = ""

; Will the script output continous content?
; Default: false
tail = true
interval = 5
format = <label>
;format-prefix = 
label = %output%
double-click-left = networkmanager_dmenu &

[module/launcher]
type = custom/text
content = " "
content-foreground = ${color.white}
click-left = rofi -show drun &

[module/powermenu]
type = custom/text
content = ""
content-foreground = ${color.red}
content-padding = 1
click-left = $HOME/dotfiles/Scripts/powermenu.sh &

[module/sep]
type = custom/text
content = ""
content-padding = 1
content-foreground = ${color.yellow}

[module/github]
type = custom/script
exec = $HOME/dotfiles/Scripts/github.sh
label = %output%
format = <label>
format-prefix = " "
click-left = xdg-open https://www.github.com/yoelvp &

